# Generated by Django 4.0.6 on 2022-08-24 03:24

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 20 characters or fewer. Letters, digits and ./_ only.', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(flags=re.RegexFlag['ASCII'], message='Enter a valid username. This value may contain only English letters, numbers, and _/. character; only a letter or digit character at the begining and at the end.', regex='^[a-zA-Z0-9](_(?![_.])|\\.(?![_.])|[a-zA-Z0-9]){2,18}[a-zA-Z0-9]$')], verbose_name='username'),
        ),
    ]
